import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseEquipment } from '../src/parse/equipment.js';
import { parseGear } from '../src/parse/gear.js';
import { parseMonsters } from '../src/parse/monsters.js';
import { parseSpells } from '../src/parse/spells.js';
import type { ParseProblem } from '../src/schemas.js';

/**
 * Parse the vendored SRD markdown into JSON, and fail loudly if it does not
 * come out whole.
 *
 * The parsers run inside the test suite already, so this exists for two other
 * reasons: to write the parsed data to disk for anything that would rather read
 * JSON than re-parse 1.9MB of markdown, and to give re-vendoring a single
 * command that reports what broke.
 *
 * It asserts counts rather than only the absence of problems. A parser that
 * silently skips everything reports no problems at all, which is exactly how
 * `animals.md` once yielded zero creatures.
 */

const here = dirname(fileURLToPath(import.meta.url));
const raw = (file: string) => readFileSync(join(here, '..', 'raw', file), 'utf8');
const outDir = join(here, '..', 'src', 'generated');

/** What each source must yield. A shortfall is a parser regression. */
const EXPECTED = {
  spells: 339,
  monsters: 235,
  animals: 95,
  weapons: 38,
  armor: 13,
  gear: 82,
  ammunition: 5,
  tools: 25,
} as const;

function report(label: string, count: number, expected: number, problems: readonly ParseProblem[]): string[] {
  const failures: string[] = [];

  for (const problem of problems) {
    failures.push(`${label}: ${problem.entry} — ${problem.message}`);
  }
  if (count !== expected) {
    failures.push(`${label}: parsed ${count}, expected ${expected}`);
  }

  process.stdout.write(`${label.padEnd(10)} ${String(count).padStart(4)}  ${count === expected && problems.length === 0 ? 'ok' : 'FAILED'}\n`);
  return failures;
}

const spells = parseSpells(raw('spells.md'), 'spells.md');
const monsters = parseMonsters(raw('monsters-A-Z.md'), 'monsters-A-Z.md');
const animals = parseMonsters(raw('animals.md'), 'animals.md');
const equipment = parseEquipment(raw('equipment.md'), 'equipment.md');
const gear = parseGear(raw('equipment.md'), 'equipment.md');

const failures = [
  ...report('spells', spells.items.length, EXPECTED.spells, spells.problems),
  ...report('monsters', monsters.items.length, EXPECTED.monsters, monsters.problems),
  ...report('animals', animals.items.length, EXPECTED.animals, animals.problems),
  ...report('weapons', equipment.weapons.length, EXPECTED.weapons, equipment.problems),
  ...report('armor', equipment.armor.length, EXPECTED.armor, []),
  ...report('gear', gear.gear.length, EXPECTED.gear, gear.problems),
  ...report('ammunition', gear.ammunition.length, EXPECTED.ammunition, []),
  ...report('tools', gear.tools.length, EXPECTED.tools, []),
];

if (failures.length > 0) {
  process.stderr.write(`\n${failures.length} problem(s):\n${failures.map((f) => `  ${f}`).join('\n')}\n`);
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });
const write = (name: string, data: unknown): void => {
  writeFileSync(join(outDir, `${name}.json`), `${JSON.stringify(data, null, 2)}\n`, 'utf8');
};

write('spells', spells.items);
write('monsters', [...monsters.items, ...animals.items]);
write('weapons', equipment.weapons);
write('armor', equipment.armor);
write('gear', gear.gear);
write('ammunition', gear.ammunition);
write('tools', gear.tools);

/**
 * The engine is pure and cannot read a file at runtime, so the data it needs
 * ships as TypeScript. Gear descriptions are prose for the narration layer and
 * are left in the JSON; the index carries only what inventory arithmetic
 * needs — identity, weight, cost, and the variants that are bought separately.
 */
const indexFile = (
  file: string,
  constant: string,
  type: string,
  banner: string,
  rows: readonly unknown[],
): void => {
  const lines = [
    `import type { ${type} } from './schemas.js';`,
    '',
    '/**',
    banner,
    ' *',
    ' * Generated by `npm run srd:ingest`. Do not edit by hand.',
    ' */',
    `export const ${constant}: readonly ${type}[] = [`,
    ...rows.map((row) => `  ${JSON.stringify(row)},`),
    '];',
    '',
  ];
  writeFileSync(join(here, '..', 'src', `${file}.ts`), lines.join('\n'), 'utf8');
};

indexFile(
  'gear-index',
  'GEAR',
  'GearIndexEntry',
  ' * Every item in the Adventuring Gear table: id, name, weight, cost, variants.',
  gear.gear.map(({ description: _description, ...rest }) => rest),
);
indexFile(
  'tool-index',
  'TOOLS',
  'Tool',
  ' * Every tool, with its ability, uses, craft list and variants.',
  gear.tools,
);
indexFile(
  'ammunition-index',
  'AMMUNITION',
  'Ammunition',
  ' * Every row of the Ammunition table: id, name, how many a purchase buys,',
  gear.ammunition,
);

process.stdout.write(`\nwrote JSON to ${outDir}\n`);
