import { readFileSync, writeFileSync } from 'node:fs';

/**
 * Emit a compact, typed spell index the engine can import without I/O.
 *
 * The engine is pure: no filesystem, no JSON loading at runtime. Creation
 * needs only five fields to validate a spell choice, so those five are
 * generated into a module rather than the whole 1.4MB of parsed spell text.
 */
const spells = JSON.parse(readFileSync('packages/srd/src/generated/spells.json', 'utf8'));
const rows = spells
  .map((s) => ({ id: s.id, name: s.name, level: s.level, school: s.school, classes: s.classes }))
  .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));

const body = rows
  .map(
    (r) =>
      `  { id: ${JSON.stringify(r.id)}, name: ${JSON.stringify(r.name)}, level: ${r.level}, school: ${JSON.stringify(r.school)}, classes: [${r.classes.map((c) => JSON.stringify(c)).join(', ')}] },`,
  )
  .join('\n');

writeFileSync(
  'packages/srd/src/spell-index.ts',
  `/**
 * A compact index of every SRD spell: id, name, level, school, class lists.
 *
 * Generated by \`scripts/spell-index.mjs\` from the parsed spell data. It exists
 * because the engine is pure — it cannot read a file or import JSON at runtime
 * — and character creation needs to check that a chosen spell exists, is on
 * the right class list, and is of the right level and school.
 *
 * Do not edit by hand. Re-run the script after \`srd:ingest\`.
 */

export interface SpellIndexEntry {
  readonly id: string;
  readonly name: string;
  /** 0 for a cantrip. */
  readonly level: number;
  readonly school: string;
  /** Lower-cased class slugs the spell appears on. */
  readonly classes: readonly string[];
}

export const SPELL_INDEX: readonly SpellIndexEntry[] = [
${body}
];

const BY_ID = new Map(SPELL_INDEX.map((spell) => [spell.id, spell]));

export const spellById = (id: string): SpellIndexEntry | null => BY_ID.get(id) ?? null;

/** Every spell on a class's list, which is how eligibility is checked. */
export const spellsForClass = (classId: string): readonly SpellIndexEntry[] =>
  SPELL_INDEX.filter((spell) => spell.classes.includes(classId));
`,
  'utf8',
);

console.log(`wrote ${rows.length} spells to packages/srd/src/spell-index.ts`);

/**
 * The same treatment for armour: creation needs to turn "Chain Mail" in an
 * equipment package into the record Armour Class is derived from, and the
 * engine cannot read a file to do it.
 */
const armor = JSON.parse(readFileSync('packages/srd/src/generated/armor.json', 'utf8'));
const armorBody = armor
  .map((a) => `  ${JSON.stringify(a)},`)
  .join('\n');

writeFileSync(
  'packages/srd/src/armor-index.ts',
  `import type { Armor } from './schemas.js';

/**
 * Every suit of armour and the shield, as parsed.
 *
 * Generated by \`scripts/spell-index.mjs\`. It exists for the same reason the
 * spell index does: the engine is pure and cannot read a file at runtime, but
 * character creation has to turn a package entry named "Chain Mail" into the
 * record Armour Class derives from.
 *
 * Do not edit by hand.
 */
export const ARMOR: readonly Armor[] = [
${armorBody}
];

export const armorByName = (name: string): Armor | null =>
  ARMOR.find((piece) => piece.name === name) ?? null;
`,
  'utf8',
);
console.log(`wrote ${armor.length} armour entries to packages/srd/src/armor-index.ts`);

/** Weapons, for the same reason: a character owns them and the engine is pure. */
const weapons = JSON.parse(readFileSync('packages/srd/src/generated/weapons.json', 'utf8'));
writeFileSync(
  'packages/srd/src/weapon-index.ts',
  `import type { Weapon } from './schemas.js';

/**
 * Every weapon, as parsed.
 *
 * Generated by \`scripts/spell-index.mjs\`. The engine is pure and cannot read a
 * file at runtime, but a character's pack has daggers in it.
 *
 * Do not edit by hand.
 */
export const WEAPONS: readonly Weapon[] = [
${weapons.map((w) => `  ${JSON.stringify(w)},`).join('\n')}
];

export const weaponById = (id: string): Weapon | null =>
  WEAPONS.find((weapon) => weapon.id === id) ?? null;
`,
  'utf8',
);
console.log(`wrote ${weapons.length} weapons to packages/srd/src/weapon-index.ts`);
