import type { Ammunition } from './schemas.js';

/**
 * Every row of the Ammunition table: id, name, how many a purchase buys,
 *
 * Generated by `pnpm srd:ingest`. Do not edit by hand.
 */
export const AMMUNITION: readonly Ammunition[] = [
  {"id":"arrows","name":"Arrows","amount":20,"storage":"Quiver","weight":{"kind":"lb","value":1},"cost":{"kind":"cost","value":{"amount":1,"currency":"gp"}}},
  {"id":"bolts","name":"Bolts","amount":20,"storage":"Case","weight":{"kind":"lb","value":1.5},"cost":{"kind":"cost","value":{"amount":1,"currency":"gp"}}},
  {"id":"bullets-firearm","name":"Bullets, Firearm","amount":10,"storage":"Pouch","weight":{"kind":"lb","value":2},"cost":{"kind":"cost","value":{"amount":3,"currency":"gp"}}},
  {"id":"bullets-sling","name":"Bullets, Sling","amount":20,"storage":"Pouch","weight":{"kind":"lb","value":1.5},"cost":{"kind":"cost","value":{"amount":4,"currency":"cp"}}},
  {"id":"needles","name":"Needles","amount":50,"storage":"Pouch","weight":{"kind":"lb","value":1},"cost":{"kind":"cost","value":{"amount":1,"currency":"gp"}}},
];
