import type { Armor } from './schemas.js';

/**
 * Every suit of armour and the shield, as parsed.
 *
 * Generated by `scripts/spell-index.mjs`. It exists for the same reason the
 * spell index does: the engine is pure and cannot read a file at runtime, but
 * character creation has to turn a package entry named "Chain Mail" into the
 * record Armour Class derives from.
 *
 * Do not edit by hand.
 */
export const ARMOR: readonly Armor[] = [
  {"id":"padded-armor","name":"Padded Armor","category":"light","baseAc":11,"acBonus":null,"addsDexModifier":true,"maxDexBonus":null,"strengthRequirement":null,"stealthDisadvantage":true,"weightLb":8,"cost":{"amount":5,"currency":"gp"}},
  {"id":"leather-armor","name":"Leather Armor","category":"light","baseAc":11,"acBonus":null,"addsDexModifier":true,"maxDexBonus":null,"strengthRequirement":null,"stealthDisadvantage":false,"weightLb":10,"cost":{"amount":10,"currency":"gp"}},
  {"id":"studded-leather-armor","name":"Studded Leather Armor","category":"light","baseAc":12,"acBonus":null,"addsDexModifier":true,"maxDexBonus":null,"strengthRequirement":null,"stealthDisadvantage":false,"weightLb":13,"cost":{"amount":45,"currency":"gp"}},
  {"id":"hide-armor","name":"Hide Armor","category":"medium","baseAc":12,"acBonus":null,"addsDexModifier":true,"maxDexBonus":2,"strengthRequirement":null,"stealthDisadvantage":false,"weightLb":12,"cost":{"amount":10,"currency":"gp"}},
  {"id":"chain-shirt","name":"Chain Shirt","category":"medium","baseAc":13,"acBonus":null,"addsDexModifier":true,"maxDexBonus":2,"strengthRequirement":null,"stealthDisadvantage":false,"weightLb":20,"cost":{"amount":50,"currency":"gp"}},
  {"id":"scale-mail","name":"Scale Mail","category":"medium","baseAc":14,"acBonus":null,"addsDexModifier":true,"maxDexBonus":2,"strengthRequirement":null,"stealthDisadvantage":true,"weightLb":45,"cost":{"amount":50,"currency":"gp"}},
  {"id":"breastplate","name":"Breastplate","category":"medium","baseAc":14,"acBonus":null,"addsDexModifier":true,"maxDexBonus":2,"strengthRequirement":null,"stealthDisadvantage":false,"weightLb":20,"cost":{"amount":400,"currency":"gp"}},
  {"id":"half-plate-armor","name":"Half Plate Armor","category":"medium","baseAc":15,"acBonus":null,"addsDexModifier":true,"maxDexBonus":2,"strengthRequirement":null,"stealthDisadvantage":true,"weightLb":40,"cost":{"amount":750,"currency":"gp"}},
  {"id":"ring-mail","name":"Ring Mail","category":"heavy","baseAc":14,"acBonus":null,"addsDexModifier":false,"maxDexBonus":null,"strengthRequirement":null,"stealthDisadvantage":true,"weightLb":40,"cost":{"amount":30,"currency":"gp"}},
  {"id":"chain-mail","name":"Chain Mail","category":"heavy","baseAc":16,"acBonus":null,"addsDexModifier":false,"maxDexBonus":null,"strengthRequirement":13,"stealthDisadvantage":true,"weightLb":55,"cost":{"amount":75,"currency":"gp"}},
  {"id":"splint-armor","name":"Splint Armor","category":"heavy","baseAc":17,"acBonus":null,"addsDexModifier":false,"maxDexBonus":null,"strengthRequirement":15,"stealthDisadvantage":true,"weightLb":60,"cost":{"amount":200,"currency":"gp"}},
  {"id":"plate-armor","name":"Plate Armor","category":"heavy","baseAc":18,"acBonus":null,"addsDexModifier":false,"maxDexBonus":null,"strengthRequirement":15,"stealthDisadvantage":true,"weightLb":65,"cost":{"amount":1500,"currency":"gp"}},
  {"id":"shield","name":"Shield","category":"shield","baseAc":null,"acBonus":2,"addsDexModifier":false,"maxDexBonus":null,"strengthRequirement":null,"stealthDisadvantage":false,"weightLb":6,"cost":{"amount":10,"currency":"gp"}},
];

export const armorByName = (name: string): Armor | null =>
  ARMOR.find((piece) => piece.name === name) ?? null;
